/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 1d4acf4c8c8b7d4b229672fd5ff0f86d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		OPENAI_API_KEY: string;
		GATEWAY_BASE_URL: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "GATEWAY_BASE_URL">> {}
}
